diffusion:
  sampler: ddpm
  steps: 10000
  noise_schedule: sigmoid
  model_mean_type: epsilon 
  model_var_type: fixed_small
  dynamic_threshold: False
  clip_denoised: True
  rescale_timesteps: False
  timestep_respacing: 10000

model:
  in_node_features: 4
  in_edge_features: 6
  sigma_embed_dim: 32
  sh_lmax: 2
  ns: 32
  nv: 32
  num_conv_layers: 4 
  max_radius: 5
  radius_embed_dim: 50
  scale_by_sigma: True
  second_order_repr: True
  batch_norm: True
  residual: True

data:
  path: dataset
  device: 'cpu'
  save_ckpt: True
  coarse_grain: True
  

conditioning:
  method: ps
  params:
    scale: 0.3

measurement:
  operator:
    name: coarse_grain
    n_atoms: 10000
    n_monomers: 50
    n_polymers: 100
  noise: 
    name: gaussian
    sigma: 0.05

train:
  gpu_id: 0
  save: False
  lr: 1e-4
  epochs: 1
  batch_size: 2
  checkpt_freq: 1
  checkpt_epoch: 1
  savepath: "/home/gmcherch/denoising-backmapping/save"