diffusion:
  sampler: ddpm
  steps: 10000
  noise_schedule: sigmoid
  model_mean_type: epsilon 
  model_var_type: fixed_small
  dynamic_threshold: False
  clip_denoised: True
  rescale_timesteps: False
  timestep_respacing: 10000

model:
  in_node_features: 11
  in_edge_features: 5
  sigma_embed_dim: 32
  sh_lmax: 2
  ns: 32
  nv: 32
  num_conv_layers: 8
  max_radius: 6
  radius_embed_dim: 25
  scale_by_sigma: True
  second_order_repr: True
  batch_norm: True
  residual: True
  model_path: None

data:
  path: dataset/cPB_10C_10M
  device: 'cpu'
  save_ckpt: True
  coarse_grain: True
  

conditioning:
  method: ps
  params:
    scale: 0.1

measurement:
  operator:
    name: coarse_grain
    
  noise: 
    name: gaussian
    sigma: 0.05

train:
  gpu_id: 0
  save: True
  lr: 1e-4
  epochs: 1000
  batch_size: 4
  checkpt_freq: 1
  checkpt_epoch: 1
  savepath: '/home/gmcherch/denoising-backmapping/save'